//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.GalleryModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GalleryEntities : DbContext
    {
        public GalleryEntities()
            : base("name=GalleryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GY_Albums> GY_Albums { get; set; }
        public DbSet<GY_Audios> GY_Audios { get; set; }
        public DbSet<GY_AudioSet> GY_AudioSet { get; set; }
        public DbSet<GY_Drives> GY_Drives { get; set; }
        public DbSet<GY_Events> GY_Events { get; set; }
        public DbSet<GY_Files> GY_Files { get; set; }
        public DbSet<GY_FileTypes> GY_FileTypes { get; set; }
        public DbSet<GY_Folders> GY_Folders { get; set; }
        public DbSet<GY_LayerProperties> GY_LayerProperties { get; set; }
        public DbSet<GY_Layers> GY_Layers { get; set; }
        public DbSet<GY_Photos> GY_Photos { get; set; }
        public DbSet<GY_SlideProperties> GY_SlideProperties { get; set; }
        public DbSet<GY_Slides> GY_Slides { get; set; }
        public DbSet<GY_Videos> GY_Videos { get; set; }
        public DbSet<GY_VideoSet> GY_VideoSet { get; set; }
        public DbSet<GY_AudioCategories> GY_AudioCategories { get; set; }
        public DbSet<GY_VideoCategories> GY_VideoCategories { get; set; }
    }
}
