//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.GalleryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GY_Albums
    {
        public GY_Albums()
        {
            this.GY_Photos = new HashSet<GY_Photos>();
        }
    
        public int AlbumID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> TakenOn { get; set; }
        public System.DateTime AddedOn { get; set; }
        public bool Hide { get; set; }
        public string Tags { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string Locale { get; set; }
    
        public virtual GY_Events GY_Events { get; set; }
        public virtual ICollection<GY_Photos> GY_Photos { get; set; }
    }
}
