//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.GalleryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GY_AudioCategories
    {
        public GY_AudioCategories()
        {
            this.GY_ChildAudioCategories = new HashSet<GY_AudioCategories>();
            this.GY_Audios = new HashSet<GY_Audios>();
            this.GY_AudioSet = new HashSet<GY_AudioSet>();
        }
    
        public int AudioCategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Hide { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string Locale { get; set; }
        public Nullable<int> ParentAudioCategoryID { get; set; }
    
        public virtual ICollection<GY_AudioCategories> GY_ChildAudioCategories { get; set; }
        public virtual GY_AudioCategories GY_ParentAudioCategory { get; set; }
        public virtual ICollection<GY_Audios> GY_Audios { get; set; }
        public virtual ICollection<GY_AudioSet> GY_AudioSet { get; set; }
    }
}
