//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.GalleryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GY_Drives
    {
        public GY_Drives()
        {
            this.GY_Files = new HashSet<GY_Files>();
            this.GY_Folders = new HashSet<GY_Folders>();
        }
    
        public int DriveID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Hide { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string Locale { get; set; }
    
        public virtual ICollection<GY_Files> GY_Files { get; set; }
        public virtual ICollection<GY_Folders> GY_Folders { get; set; }
    }
}
