//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.GalleryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GY_Events
    {
        public GY_Events()
        {
            this.GY_Albums = new HashSet<GY_Albums>();
        }
    
        public int EventID { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public string SubDescription { get; set; }
        public Nullable<System.DateTime> StartsOn { get; set; }
        public Nullable<System.DateTime> EndsOn { get; set; }
        public string Location { get; set; }
        public string Tags { get; set; }
        public bool Hide { get; set; }
        public int EventTypeID { get; set; }
        public bool UseExternalForm { get; set; }
        public string ExternalFormEmbedCode { get; set; }
        public string ExternalFormURL { get; set; }
        public Nullable<int> ExternalFormID { get; set; }
        public bool PopUpExternalForm { get; set; }
        public Nullable<System.DateTime> RegistrationStartDateTime { get; set; }
        public Nullable<System.DateTime> RegistrationEndDateTime { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string Locale { get; set; }
    
        public virtual ICollection<GY_Albums> GY_Albums { get; set; }
    }
}
