//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.GalleryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GY_FileTypes
    {
        public GY_FileTypes()
        {
            this.GY_Files = new HashSet<GY_Files>();
        }
    
        public int FileTypeID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Hide { get; set; }
    
        public virtual ICollection<GY_Files> GY_Files { get; set; }
    }
}
