//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.GalleryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GY_Folders
    {
        public GY_Folders()
        {
            this.GY_Files = new HashSet<GY_Files>();
            this.ChildFolders = new HashSet<GY_Folders>();
        }
    
        public long FolderID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Hide { get; set; }
        public int DriveID { get; set; }
        public string Tags { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<long> ParentFolderID { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string Locale { get; set; }
    
        public virtual GY_Drives GY_Drives { get; set; }
        public virtual ICollection<GY_Files> GY_Files { get; set; }
        public virtual ICollection<GY_Folders> ChildFolders { get; set; }
        public virtual GY_Folders ParentFolder { get; set; }
    }
}
