//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.GalleryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GY_Slides
    {
        public GY_Slides()
        {
            this.GY_Layers = new HashSet<GY_Layers>();
            this.GY_SlideProperties = new HashSet<GY_SlideProperties>();
        }
    
        public long SlideID { get; set; }
        public string Title { get; set; }
        public int Position { get; set; }
        public string BGImageURL { get; set; }
        public string BGImageThumbURL { get; set; }
        public string BGImageDummyURL { get; set; }
        public bool Hide { get; set; }
    
        public virtual ICollection<GY_Layers> GY_Layers { get; set; }
        public virtual ICollection<GY_SlideProperties> GY_SlideProperties { get; set; }
    }
}
