//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL {
    
    
    public partial class Default {
        
        /// <summary>
        /// HomePageTopBlockPostEmbedComponent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Components.Media.Nested.PostEmbedComponent HomePageTopBlockPostEmbedComponent;
        
        /// <summary>
        /// HomePagePostEmbedComponent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Components.Media.Nested.PostEmbedComponent HomePagePostEmbedComponent;
        
        /// <summary>
        /// RecentVideosComponent1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Components.Gallery.RecentVideosComponent RecentVideosComponent1;
        
        /// <summary>
        /// HomePageBottomBlockPostEmbedComponent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Components.Media.Nested.PostEmbedComponent HomePageBottomBlockPostEmbedComponent;
    }
}
