//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.ShoppingCartModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_AvailabilityTypes
    {
        public SC_AvailabilityTypes()
        {
            this.SC_Products = new HashSet<SC_Products>();
        }
    
        public int AvailabilityTypeID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Hide { get; set; }
        public string ColorName { get; set; }
    
        public virtual ICollection<SC_Products> SC_Products { get; set; }
    }
}
