//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.ShoppingCartModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_Brands
    {
        public SC_Brands()
        {
            this.SC_Coupons = new HashSet<SC_Coupons>();
            this.SC_DiscountRules = new HashSet<SC_DiscountRules>();
            this.SC_Products = new HashSet<SC_Products>();
        }
    
        public int BrandID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public bool Hide { get; set; }
    
        public virtual ICollection<SC_Coupons> SC_Coupons { get; set; }
        public virtual ICollection<SC_DiscountRules> SC_DiscountRules { get; set; }
        public virtual ICollection<SC_Products> SC_Products { get; set; }
    }
}
