//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.ShoppingCartModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_DiscountRanges
    {
        public long DiscountRangeID { get; set; }
        public double LowerRange { get; set; }
        public double UpperRange { get; set; }
        public int ProductID { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> FixedPrice { get; set; }
    
        public virtual SC_Products SC_Products { get; set; }
    }
}
