//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.ShoppingCartModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_Orders
    {
        public SC_Orders()
        {
            this.SC_GuestOrders = new HashSet<SC_GuestOrders>();
            this.SC_OrderDetails = new HashSet<SC_OrderDetails>();
            this.SC_UserOrders = new HashSet<SC_UserOrders>();
        }
    
        public string OrderNumber { get; set; }
        public System.DateTime DateTime { get; set; }
        public string ShippingAddress { get; set; }
        public string BillingAddress { get; set; }
        public string EmailID { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> ShipmentTypeID { get; set; }
        public double OrderTotal { get; set; }
        public double ShipmentCost { get; set; }
        public bool IsConfirmed { get; set; }
        public bool IsCancelled { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsPaid { get; set; }
        public bool IsFailed { get; set; }
        public bool IsRefund { get; set; }
        public bool IsDispatched { get; set; }
        public bool IsReturned { get; set; }
        public string ReceiptHTML { get; set; }
    
        public virtual ICollection<SC_GuestOrders> SC_GuestOrders { get; set; }
        public virtual ICollection<SC_OrderDetails> SC_OrderDetails { get; set; }
        public virtual SC_ShipmentTypes SC_ShipmentTypes { get; set; }
        public virtual ICollection<SC_UserOrders> SC_UserOrders { get; set; }
    }
}
