//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.ShoppingCartModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_ProductVideos
    {
        public long ProductVideoID { get; set; }
        public int ProductID { get; set; }
        public string YouTubeVideoURL { get; set; }
        public string OtherVideoURL { get; set; }
        public string VideoURL { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool ShowYouTubeVideo { get; set; }
        public bool ShowOtherVideo { get; set; }
        public bool ShowLocalVideo { get; set; }
        public bool Hide { get; set; }
    
        public virtual SC_Products SC_Products { get; set; }
    }
}
