//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.ShoppingCartModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_SubCategories
    {
        public SC_SubCategories()
        {
            this.SC_Colors = new HashSet<SC_Colors>();
            this.SC_Coupons = new HashSet<SC_Coupons>();
            this.SC_DiscountRules = new HashSet<SC_DiscountRules>();
            this.SC_ProductModels = new HashSet<SC_ProductModels>();
            this.SC_Products = new HashSet<SC_Products>();
            this.SC_ProductTypes = new HashSet<SC_ProductTypes>();
            this.SC_Sizes = new HashSet<SC_Sizes>();
            this.SC_Units = new HashSet<SC_Units>();
        }
    
        public int SubCategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public string ImageThumbURL { get; set; }
        public string AlternateText { get; set; }
        public int CategoryID { get; set; }
        public bool Hide { get; set; }
    
        public virtual SC_Categories SC_Categories { get; set; }
        public virtual ICollection<SC_Colors> SC_Colors { get; set; }
        public virtual ICollection<SC_Coupons> SC_Coupons { get; set; }
        public virtual ICollection<SC_DiscountRules> SC_DiscountRules { get; set; }
        public virtual ICollection<SC_ProductModels> SC_ProductModels { get; set; }
        public virtual ICollection<SC_Products> SC_Products { get; set; }
        public virtual ICollection<SC_ProductTypes> SC_ProductTypes { get; set; }
        public virtual ICollection<SC_Sizes> SC_Sizes { get; set; }
        public virtual ICollection<SC_Units> SC_Units { get; set; }
    }
}
