//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.ShoppingCartModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_ShipmentTypes
    {
        public SC_ShipmentTypes()
        {
            this.SC_Orders = new HashSet<SC_Orders>();
        }
    
        public int ShipmentTypeID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Hide { get; set; }
    
        public virtual ICollection<SC_Orders> SC_Orders { get; set; }
    }
}
