//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.ShoppingCartModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_UsersData
    {
        public long UserDataID { get; set; }
        public string Username { get; set; }
        public string UsersDataCategory { get; set; }
        public string UserData { get; set; }
        public bool Hide { get; set; }
    
        public virtual SC_Users MS_Users { get; set; }
    }
}
