//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.ShoppingCartModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_Users
    {
        public SC_Users()
        {
            this.MS_UserAdresses = new HashSet<SC_UserAdresses>();
            this.SC_Reviews = new HashSet<SC_Reviews>();
            this.SC_UserCardDetails = new HashSet<SC_UserCardDetails>();
            this.SC_UserCart = new HashSet<SC_UserCart>();
            this.SC_UserOrders = new HashSet<SC_UserOrders>();
            this.MS_UsersData = new HashSet<SC_UsersData>();
        }
    
        public string Username { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ProfilePic { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecurityAnswer { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string UserRole { get; set; }
        public Nullable<int> UserCategoryID { get; set; }
        public bool Hide { get; set; }
    
        public virtual ICollection<SC_UserAdresses> MS_UserAdresses { get; set; }
        public virtual SC_UserCategories MS_UserCategories { get; set; }
        public virtual ICollection<SC_Reviews> SC_Reviews { get; set; }
        public virtual ICollection<SC_UserCardDetails> SC_UserCardDetails { get; set; }
        public virtual ICollection<SC_UserCart> SC_UserCart { get; set; }
        public virtual ICollection<SC_UserOrders> SC_UserOrders { get; set; }
        public virtual ICollection<SC_UsersData> MS_UsersData { get; set; }
    }
}
