//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.UI.Pages.Admin.OFrame {
    
    
    public partial class Settings {
        
        /// <summary>
        /// EnableQACheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv EnableQACheckBox;
        
        /// <summary>
        /// ShowUserAddPopUpComponentCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv ShowUserAddPopUpComponentCheckBox;
        
        /// <summary>
        /// PerformanceModeDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.DropDownListAdv PerformanceModeDropDownList;
        
        /// <summary>
        /// MemoryCacheItemPriorityDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.DropDownListAdv MemoryCacheItemPriorityDropDownList;
        
        /// <summary>
        /// AllowGuestBuyCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv AllowGuestBuyCheckBox;
        
        /// <summary>
        /// UseLoginReturnURLCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv UseLoginReturnURLCheckBox;
        
        /// <summary>
        /// EnableMailSSLCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv EnableMailSSLCheckBox;
        
        /// <summary>
        /// MailSMTPCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv MailSMTPCheckBox;
        
        /// <summary>
        /// DefaultUserRegistrationCategoryDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.DropDownListAdv DefaultUserRegistrationCategoryDropDownList;
        
        /// <summary>
        /// ReloadAppDomainToolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.FormToolbar ReloadAppDomainToolbar;
        
        /// <summary>
        /// StatusMessage1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.StatusMessageJQuery StatusMessage1;
        
        /// <summary>
        /// SiteNameTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv SiteNameTextBox;
        
        /// <summary>
        /// HeaderTitleTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv HeaderTitleTextBox;
        
        /// <summary>
        /// HeaderTagLineTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv HeaderTagLineTextBox;
        
        /// <summary>
        /// ReceiptAddressEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CKEditor ReceiptAddressEditor;
        
        /// <summary>
        /// DiscussCodeTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProjectJKL.UI.UserControls.Controls.UnsafeTextBox DiscussCodeTextBox;
        
        /// <summary>
        /// GoogleAnalyticsCodeTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProjectJKL.UI.UserControls.Controls.UnsafeTextBox GoogleAnalyticsCodeTextBox;
        
        /// <summary>
        /// GoogleWebmasterToolTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv GoogleWebmasterToolTextBox;
        
        /// <summary>
        /// BingWebMasterCenterTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv BingWebMasterCenterTextBox;
        
        /// <summary>
        /// OAuthLoginCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv OAuthLoginCheckBox;
        
        /// <summary>
        /// FacebookAPIKeyTextBix control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv FacebookAPIKeyTextBix;
        
        /// <summary>
        /// FacebookSecretKeyTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv FacebookSecretKeyTextBox;
        
        /// <summary>
        /// GoogleAPIKeyTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv GoogleAPIKeyTextBox;
        
        /// <summary>
        /// GoogleSecretKeyTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv GoogleSecretKeyTextBox;
        
        /// <summary>
        /// TwitterAPIKeyTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv TwitterAPIKeyTextBox;
        
        /// <summary>
        /// TwitterSecretKeyTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv TwitterSecretKeyTextBox;
        
        /// <summary>
        /// MAIScriptTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProjectJKL.UI.UserControls.Controls.UnsafeTextBox MAIScriptTextBox;
        
        /// <summary>
        /// LogoRelativeURLTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv LogoRelativeURLTextBox;
        
        /// <summary>
        /// PerformanceTimeOutMinutesTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv PerformanceTimeOutMinutesTextBox;
        
        /// <summary>
        /// CookieTimeOutMinutesTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv CookieTimeOutMinutesTextBox;
        
        /// <summary>
        /// TargetTimeZoneIDDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.DropDownListAdv TargetTimeZoneIDDropDownList;
        
        /// <summary>
        /// IsSiteMultiLingualCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv IsSiteMultiLingualCheckBox;
        
        /// <summary>
        /// LocaleDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.Nested.LocalizationDropDownList LocaleDropDownList;
        
        /// <summary>
        /// AccessManagerSearchPatternsTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv AccessManagerSearchPatternsTextBox;
        
        /// <summary>
        /// FileEditorSearchPatternsTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv FileEditorSearchPatternsTextBox;
        
        /// <summary>
        /// HomePagePostIDTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv HomePagePostIDTextBox;
        
        /// <summary>
        /// HomePageTopBlockPostIDTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv HomePageTopBlockPostIDTextBox;
        
        /// <summary>
        /// HomePageBottomBlockPostIDTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv HomePageBottomBlockPostIDTextBox;
        
        /// <summary>
        /// AboutUsPostIDTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv AboutUsPostIDTextBox;
        
        /// <summary>
        /// ContactUsPostIDTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv ContactUsPostIDTextBox;
        
        /// <summary>
        /// KeepProductNewForDaysTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv KeepProductNewForDaysTextBox;
        
        /// <summary>
        /// ProductHotItemSoldOutCountTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv ProductHotItemSoldOutCountTextBox;
        
        /// <summary>
        /// MinimumProductRatingToShowTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv MinimumProductRatingToShowTextBox;
        
        /// <summary>
        /// MinimumCartAmountTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv MinimumCartAmountTextBox;
        
        /// <summary>
        /// ProductLockTimeOutInMinutesTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv ProductLockTimeOutInMinutesTextBox;
        
        /// <summary>
        /// MailServerTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv MailServerTextBox;
        
        /// <summary>
        /// MailLogonIDTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv MailLogonIDTextBox;
        
        /// <summary>
        /// MailLogonPasswordTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv MailLogonPasswordTextBox;
        
        /// <summary>
        /// MailServerPortTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv MailServerPortTextBox;
        
        /// <summary>
        /// WebsiteMainEmailTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv WebsiteMainEmailTextBox;
        
        /// <summary>
        /// WebsiteAdminEmailTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv WebsiteAdminEmailTextBox;
        
        /// <summary>
        /// ErrorAdminEmailTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv ErrorAdminEmailTextBox;
        
        /// <summary>
        /// FormToolbar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.FormToolbar FormToolbar1;
        
        /// <summary>
        /// StatusMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.StatusMessageJQuery StatusMessage;
    }
}
