//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.MediaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ME_Books
    {
        public ME_Books()
        {
            this.ME_Chapters = new HashSet<ME_Chapters>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Username { get; set; }
        public System.DateTime WrittenOn { get; set; }
        public bool Hide { get; set; }
        public string Tags { get; set; }
        public int BookCategoryID { get; set; }
        public Nullable<int> ImageID { get; set; }
    
        public virtual ME_BookCategories ME_BookCategories { get; set; }
        public virtual ICollection<ME_Chapters> ME_Chapters { get; set; }
    }
}
