//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.MediaModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediaEntities : DbContext
    {
        public MediaEntities()
            : base("name=MediaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ME_BookCategories> ME_BookCategories { get; set; }
        public DbSet<ME_Books> ME_Books { get; set; }
        public DbSet<ME_Chapters> ME_Chapters { get; set; }
        public DbSet<ME_Clients> ME_Clients { get; set; }
        public DbSet<ME_PortfolioCategories> ME_PortfolioCategories { get; set; }
        public DbSet<ME_Portfolios> ME_Portfolios { get; set; }
        public DbSet<ME_ProjectCategories> ME_ProjectCategories { get; set; }
        public DbSet<ME_Subscriptions> ME_Subscriptions { get; set; }
        public DbSet<ME_Testimonials> ME_Testimonials { get; set; }
        public DbSet<ME_PostCategories> ME_PostCategories { get; set; }
        public DbSet<ME_Posts> ME_Posts { get; set; }
    }
}
