//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWDARO.UI.Pages.LogOn {
    
    
    public partial class ForgotPassword {
        
        /// <summary>
        /// QAPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel QAPanel;
        
        /// <summary>
        /// SecurityQAComponent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Components.OFrameMembership.SecurityQAComponent SecurityQAComponent;
        
        /// <summary>
        /// RetrievePasswordComponent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Components.OFrameMembership.RetrievePasswordComponent RetrievePasswordComponent;
        
        /// <summary>
        /// RetrieveUsernameComponent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Components.OFrameMembership.RetrieveUsernameComponent RetrieveUsernameComponent;
    }
}
