//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWDARO.UI.UserControls.Components.OFrameMembership {
    
    
    public partial class CategorySettingsComponent {
        
        /// <summary>
        /// BoxTitleLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal BoxTitleLiteral;
        
        /// <summary>
        /// EducationAUSCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv EducationAUSCheckBox;
        
        /// <summary>
        /// WorkAUSCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv WorkAUSCheckBox;
        
        /// <summary>
        /// AddressAUSCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv AddressAUSCheckBox;
        
        /// <summary>
        /// GenderAUSCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv GenderAUSCheckBox;
        
        /// <summary>
        /// FaxAUSCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv FaxAUSCheckBox;
        
        /// <summary>
        /// DOBAUSCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv DOBAUSCheckBox;
        
        /// <summary>
        /// LandlineAUSCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv LandlineAUSCheckBox;
        
        /// <summary>
        /// MobileAUSCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv MobileAUSCheckBox;
        
        /// <summary>
        /// WebsiteAUSCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv WebsiteAUSCheckBox;
        
        /// <summary>
        /// BillingAddressAUSCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv BillingAddressAUSCheckBox;
        
        /// <summary>
        /// DeliveryAddressAUSCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.CheckBoxAdv DeliveryAddressAUSCheckBox;
    }
}
