//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWDARO.UI.UserControls.Components.OFrameMembership {
    
    
    public partial class UserEducationComponent {
        
        /// <summary>
        /// InstituteTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv InstituteTextBox;
        
        /// <summary>
        /// StreamTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv StreamTextBox;
        
        /// <summary>
        /// StartDateTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv StartDateTextBox;
        
        /// <summary>
        /// EndDateTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.TextBoxAdv EndDateTextBox;
        
        /// <summary>
        /// QualificationTypeDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Controls.DropDownListAdv QualificationTypeDropDownList;
    }
}
