//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.MembershipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_EducationQualificationTypes
    {
        public MS_EducationQualificationTypes()
        {
            this.MS_UserEducations = new HashSet<MS_UserEducations>();
        }
    
        public int EducationQualificationTypeID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Hide { get; set; }
    
        public virtual ICollection<MS_UserEducations> MS_UserEducations { get; set; }
    }
}
