//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.MembershipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Users
    {
        public MS_Users()
        {
            this.MS_UserAdresses = new HashSet<MS_UserAdresses>();
            this.MS_UserEducations = new HashSet<MS_UserEducations>();
            this.MS_UsersData = new HashSet<MS_UsersData>();
            this.MS_UserWorks = new HashSet<MS_UserWorks>();
        }
    
        public string Username { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ProfilePic { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecurityAnswer { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string UserRole { get; set; }
        public Nullable<int> UserCategoryID { get; set; }
        public bool Hide { get; set; }
    
        public virtual ICollection<MS_UserAdresses> MS_UserAdresses { get; set; }
        public virtual MS_UserCategories MS_UserCategories { get; set; }
        public virtual ICollection<MS_UserEducations> MS_UserEducations { get; set; }
        public virtual ICollection<MS_UsersData> MS_UsersData { get; set; }
        public virtual ICollection<MS_UserWorks> MS_UserWorks { get; set; }
    }
}
