//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.MembershipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_UserAdresses
    {
        public int AddressID { get; set; }
        public string Username { get; set; }
        public string AddressCategory { get; set; }
        public string StreetName { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public bool Hide { get; set; }
    
        public virtual MS_Users MS_Users { get; set; }
    }
}
