//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.MembershipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_UserCategories
    {
        public MS_UserCategories()
        {
            this.MS_Users = new HashSet<MS_Users>();
        }
    
        public int UserCategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Hide { get; set; }
    
        public virtual ICollection<MS_Users> MS_Users { get; set; }
    }
}
