//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.AppCode.DAL.MembershipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_UserEducations
    {
        public long EducationID { get; set; }
        public string Username { get; set; }
        public string InstituteName { get; set; }
        public string Stream { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int EducationQualificationTypeID { get; set; }
        public bool Hide { get; set; }
    
        public virtual MS_EducationQualificationTypes MS_EducationQualificationTypes { get; set; }
        public virtual MS_Users MS_Users { get; set; }
    }
}
