//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJKL.UI.Pages.Open.ShoppingCart.CheckOut {
    
    
    public partial class CheckOutStep2 {
        
        /// <summary>
        /// CheckOutStep2Component control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OWDARO.UI.UserControls.Components.ShoppingCart.CheckOutStep2Component CheckOutStep2Component;
    }
}
